### ISSUE TITLE
Can't work with profile not named "default"?

### ISSUE THREAD

**Issue by gunnarmorling** [decodableco/dbt-decodable#8]
Getting this error:

```
dbt run
16:20:57  Running with dbt=1.3.3
16:20:57  Found 1 model, 0 tests, 0 snapshots, 0 analyses, 273 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
16:20:57
16:20:58  Encountered an error:
Undefined 'default in decodable profile file ~/.decodable/auth
16:20:58  Traceback (most recent call last):
  File "demo/dbt-venv/lib/python3.9/site-packages/dbt/main.py", line 135, in main
    results, succeeded = handle_and_check(args)
  File "demo/dbt-venv/lib/python3.9/site-packages/dbt/main.py", line 198, in handle_and_check
    task, res = run_from_args(parsed)
  File "demo/dbt-venv/lib/python3.9/site-packages/dbt/main.py", line 245, in run_from_args
    results = task.run()
  File "demo/dbt-venv/lib/python3.9/site-packages/dbt/task/runnable.py", line 472, in run
    result = self.execute_with_hooks(selected_uids)
  File "demo/dbt-venv/lib/python3.9/site-packages/dbt/task/runnable.py", line 434, in execute_with_hooks
    self.before_run(adapter, selected_uids)
  File "demo/dbt-venv/lib/python3.9/site-packages/dbt/task/run.py", line 426, in before_run
    self.populate_adapter_cache(adapter, required_schemas)
  File "demo/dbt-venv/lib/python3.9/site-packages/dbt/task/runnable.py", line 409, in populate_adapter_cache
    adapter.set_relations_cache(self.manifest)
  File "demo/dbt-venv/lib/python3.9/site-packages/dbt/adapters/base/impl.py", line 437, in set_relations_cache
    self._relations_cache_for_schemas(manifest, required_schemas)
  File "demo/dbt-venv/lib/python3.9/site-packages/dbt/adapters/base/impl.py", line 414, in _relations_cache_for_schemas
    for relation in future.result():
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "demo/dbt-venv/lib/python3.9/site-packages/dbt/utils.py", line 480, in connected
    return func(*args, **kwargs)
  File "demo/dbt-venv/lib/python3.9/site-packages/dbt/adapters/decodable/impl.py", line 348, in list_relations_without_caching
    stream_list: List[Dict[str, Any]] = self._client().list_streams().items
  File "demo/dbt-venv/lib/python3.9/site-packages/dbt/adapters/decodable/impl.py", line 641, in _client
    self.get_thread_connection().handle
  File "demo/dbt-venv/lib/python3.9/site-packages/dbt/contracts/connection.py", line 94, in handle
    self._handle.resolve(self)
  File "demo/dbt-venv/lib/python3.9/site-packages/dbt/contracts/con
nection.py", line 116, in resolve
    return self.opener(connection)
  File "demo/dbt-venv/lib/python3.9/site-packages/dbt/adapters/decodable/connections.py", line 114, in open
    client = DecodableClientFactory.create_client(
  File "demo/dbt-venv/lib/python3.9/site-packages/decodable/client/client_factory.py", line 34, in create_client
    raise Exception(
Exception: Undefined 'default in decodable profile file ~/.decodable/auth
```

My ~/.decodable/config looks like this (note the active profile is "decodable-demo"):

```
version: 1.0.0
active-profile: decodable-demo
profiles:
    decodable-demo:
        account: decodable-demo
    default:
        account: decodable-test
```

**Comment by rmetzger** [comment]
The dbt adapter does not respect the configured `active-profile` from the `~/.decodable/config`.
This is where you set the profile:
https://github.com/decodableco/dbt-decodable/blob/main/README.md?plain=1#L40
